### ISSUE TITLE
App on Apple M1 Chip

### ISSUE THREAD

**Issue by llerch** [phhai1710/BinancePriceBar#1]
Hi,

Nice app. Unfortunately it doesn't work on apple m1 chip. When i open the App, there isn't something displayed or something.

**Comment by phhai1710** [comment]
Hi @llerch 
1. Did you tapped into ₿ icon in Touch bar Control strip?
2. Could you please try to open Preferences window by tapping into icon on the Menu bar -> Preferences and check if there are any coin pairs in the list?

**Comment by llerch** [comment]
Hi @phhai1710 

Thanks for reply. The Icon isn't in the Menu Bar. When I open the BinancePriceBar via Spotlight search I accept to open the app and then nothing happens.

**Comment by phhai1710** [comment]
Hey @llerch, I have tested on Apple M1 and it works fine. Could you please try these steps:
1. Download and tap into app icon to open app
2. In Control Strip of TouchBar, tap into ₿ icon (https://github.com/phhai1710/BinancePriceBar/raw/master/Resources/touchbar.gif?raw=true)
3. Tap into B logo in Menu bar and select Preferences (https://github.com/phhai1710/BinancePriceBar/raw/master/Resources/icon_menu_bar.png?raw=true)
4. Add new coin pair and Save (https://github.com/phhai1710/BinancePriceBar/raw/master/Resources/Preferences.png)

I have updated the ReadMe file, so you can check it again. If you still facing this issue, please record a video and send me, that would be great.

**Comment by llerch** [comment]
Hi @phhai1710 

Thanks for your reply. Its working now. I downloaded it again. Then when I opend i navigate to Setting -> Security and allowed opening the app, because Macos said "Can't Be Opened Because Apple Cannot Check For Malicious Software". Now it works well and it's ultraa Nice :).

**Comment by phhai1710** [comment]
@llerch you are welcome 👍🏻
